/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedCIndexRouteImport } from './routes/_authenticated/c.index'
import { Route as AuthenticatedCPostRouteImport } from './routes/_authenticated/c.post'
import { Route as AuthenticatedCProblemsRouteImport } from './routes/_authenticated/c.problems'
import { Route as AuthenticatedChatJobIdRouteImport } from './routes/_authenticated/chat.$jobId'
import { Route as AuthenticatedEIndexRouteImport } from './routes/_authenticated/e.index'
import { Route as AuthenticatedEJobsRouteImport } from './routes/_authenticated/e.jobs'
import { Route as AuthenticatedEOnboardingRouteImport } from './routes/_authenticated/e.onboarding'
import { Route as ApiPublicRazorpayWebhookRouteImport } from './routes/api/public/razorpay-webhook'
import { Route as ApiPublicStripeWebhookRouteImport } from './routes/api/public/stripe-webhook'
import { Route as AuthenticatedCProblemIdRouteImport } from './routes/_authenticated/c.problem.$id'
import { Route as AuthenticatedEQuoteIdRouteImport } from './routes/_authenticated/e.quote.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCIndexRoute = AuthenticatedCIndexRouteImport.update({
  id: '/c/',
  path: '/c/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCPostRoute = AuthenticatedCPostRouteImport.update({
  id: '/c/post',
  path: '/c/post',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCProblemsRoute = AuthenticatedCProblemsRouteImport.update({
  id: '/c/problems',
  path: '/c/problems',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChatJobIdRoute = AuthenticatedChatJobIdRouteImport.update({
  id: '/chat/$jobId',
  path: '/chat/$jobId',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEIndexRoute = AuthenticatedEIndexRouteImport.update({
  id: '/e/',
  path: '/e/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEJobsRoute = AuthenticatedEJobsRouteImport.update({
  id: '/e/jobs',
  path: '/e/jobs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEOnboardingRoute =
  AuthenticatedEOnboardingRouteImport.update({
    id: '/e/onboarding',
    path: '/e/onboarding',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicRazorpayWebhookRoute =
  ApiPublicRazorpayWebhookRouteImport.update({
    id: '/api/public/razorpay-webhook',
    path: '/api/public/razorpay-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicStripeWebhookRoute = ApiPublicStripeWebhookRouteImport.update({
  id: '/api/public/stripe-webhook',
  path: '/api/public/stripe-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCProblemIdRoute = AuthenticatedCProblemIdRouteImport.update({
  id: '/c/problem/$id',
  path: '/c/problem/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEQuoteIdRoute = AuthenticatedEQuoteIdRouteImport.update({
  id: '/e/quote/$id',
  path: '/e/quote/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/c/post': typeof AuthenticatedCPostRoute
  '/c/problems': typeof AuthenticatedCProblemsRoute
  '/chat/$jobId': typeof AuthenticatedChatJobIdRoute
  '/e/jobs': typeof AuthenticatedEJobsRoute
  '/e/onboarding': typeof AuthenticatedEOnboardingRoute
  '/api/public/razorpay-webhook': typeof ApiPublicRazorpayWebhookRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/c/': typeof AuthenticatedCIndexRoute
  '/e/': typeof AuthenticatedEIndexRoute
  '/c/problem/$id': typeof AuthenticatedCProblemIdRoute
  '/e/quote/$id': typeof AuthenticatedEQuoteIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/c/post': typeof AuthenticatedCPostRoute
  '/c/problems': typeof AuthenticatedCProblemsRoute
  '/chat/$jobId': typeof AuthenticatedChatJobIdRoute
  '/e/jobs': typeof AuthenticatedEJobsRoute
  '/e/onboarding': typeof AuthenticatedEOnboardingRoute
  '/api/public/razorpay-webhook': typeof ApiPublicRazorpayWebhookRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/c': typeof AuthenticatedCIndexRoute
  '/e': typeof AuthenticatedEIndexRoute
  '/c/problem/$id': typeof AuthenticatedCProblemIdRoute
  '/e/quote/$id': typeof AuthenticatedEQuoteIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/c/post': typeof AuthenticatedCPostRoute
  '/_authenticated/c/problems': typeof AuthenticatedCProblemsRoute
  '/_authenticated/chat/$jobId': typeof AuthenticatedChatJobIdRoute
  '/_authenticated/e/jobs': typeof AuthenticatedEJobsRoute
  '/_authenticated/e/onboarding': typeof AuthenticatedEOnboardingRoute
  '/api/public/razorpay-webhook': typeof ApiPublicRazorpayWebhookRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/c/': typeof AuthenticatedCIndexRoute
  '/_authenticated/e/': typeof AuthenticatedEIndexRoute
  '/_authenticated/c/problem/$id': typeof AuthenticatedCProblemIdRoute
  '/_authenticated/e/quote/$id': typeof AuthenticatedEQuoteIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/c/post'
    | '/c/problems'
    | '/chat/$jobId'
    | '/e/jobs'
    | '/e/onboarding'
    | '/api/public/razorpay-webhook'
    | '/api/public/stripe-webhook'
    | '/admin/'
    | '/c/'
    | '/e/'
    | '/c/problem/$id'
    | '/e/quote/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/c/post'
    | '/c/problems'
    | '/chat/$jobId'
    | '/e/jobs'
    | '/e/onboarding'
    | '/api/public/razorpay-webhook'
    | '/api/public/stripe-webhook'
    | '/admin'
    | '/c'
    | '/e'
    | '/c/problem/$id'
    | '/e/quote/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/c/post'
    | '/_authenticated/c/problems'
    | '/_authenticated/chat/$jobId'
    | '/_authenticated/e/jobs'
    | '/_authenticated/e/onboarding'
    | '/api/public/razorpay-webhook'
    | '/api/public/stripe-webhook'
    | '/_authenticated/admin/'
    | '/_authenticated/c/'
    | '/_authenticated/e/'
    | '/_authenticated/c/problem/$id'
    | '/_authenticated/e/quote/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicRazorpayWebhookRoute: typeof ApiPublicRazorpayWebhookRoute
  ApiPublicStripeWebhookRoute: typeof ApiPublicStripeWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/c/': {
      id: '/_authenticated/c/'
      path: '/c'
      fullPath: '/c/'
      preLoaderRoute: typeof AuthenticatedCIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/c/post': {
      id: '/_authenticated/c/post'
      path: '/c/post'
      fullPath: '/c/post'
      preLoaderRoute: typeof AuthenticatedCPostRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/c/problems': {
      id: '/_authenticated/c/problems'
      path: '/c/problems'
      fullPath: '/c/problems'
      preLoaderRoute: typeof AuthenticatedCProblemsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chat/$jobId': {
      id: '/_authenticated/chat/$jobId'
      path: '/chat/$jobId'
      fullPath: '/chat/$jobId'
      preLoaderRoute: typeof AuthenticatedChatJobIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/e/': {
      id: '/_authenticated/e/'
      path: '/e'
      fullPath: '/e/'
      preLoaderRoute: typeof AuthenticatedEIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/e/jobs': {
      id: '/_authenticated/e/jobs'
      path: '/e/jobs'
      fullPath: '/e/jobs'
      preLoaderRoute: typeof AuthenticatedEJobsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/e/onboarding': {
      id: '/_authenticated/e/onboarding'
      path: '/e/onboarding'
      fullPath: '/e/onboarding'
      preLoaderRoute: typeof AuthenticatedEOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/razorpay-webhook': {
      id: '/api/public/razorpay-webhook'
      path: '/api/public/razorpay-webhook'
      fullPath: '/api/public/razorpay-webhook'
      preLoaderRoute: typeof ApiPublicRazorpayWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/stripe-webhook': {
      id: '/api/public/stripe-webhook'
      path: '/api/public/stripe-webhook'
      fullPath: '/api/public/stripe-webhook'
      preLoaderRoute: typeof ApiPublicStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/c/problem/$id': {
      id: '/_authenticated/c/problem/$id'
      path: '/c/problem/$id'
      fullPath: '/c/problem/$id'
      preLoaderRoute: typeof AuthenticatedCProblemIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/e/quote/$id': {
      id: '/_authenticated/e/quote/$id'
      path: '/e/quote/$id'
      fullPath: '/e/quote/$id'
      preLoaderRoute: typeof AuthenticatedEQuoteIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCPostRoute: typeof AuthenticatedCPostRoute
  AuthenticatedCProblemsRoute: typeof AuthenticatedCProblemsRoute
  AuthenticatedChatJobIdRoute: typeof AuthenticatedChatJobIdRoute
  AuthenticatedEJobsRoute: typeof AuthenticatedEJobsRoute
  AuthenticatedEOnboardingRoute: typeof AuthenticatedEOnboardingRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedCIndexRoute: typeof AuthenticatedCIndexRoute
  AuthenticatedEIndexRoute: typeof AuthenticatedEIndexRoute
  AuthenticatedCProblemIdRoute: typeof AuthenticatedCProblemIdRoute
  AuthenticatedEQuoteIdRoute: typeof AuthenticatedEQuoteIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCPostRoute: AuthenticatedCPostRoute,
  AuthenticatedCProblemsRoute: AuthenticatedCProblemsRoute,
  AuthenticatedChatJobIdRoute: AuthenticatedChatJobIdRoute,
  AuthenticatedEJobsRoute: AuthenticatedEJobsRoute,
  AuthenticatedEOnboardingRoute: AuthenticatedEOnboardingRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedCIndexRoute: AuthenticatedCIndexRoute,
  AuthenticatedEIndexRoute: AuthenticatedEIndexRoute,
  AuthenticatedCProblemIdRoute: AuthenticatedCProblemIdRoute,
  AuthenticatedEQuoteIdRoute: AuthenticatedEQuoteIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicRazorpayWebhookRoute: ApiPublicRazorpayWebhookRoute,
  ApiPublicStripeWebhookRoute: ApiPublicStripeWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
