// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ujedfynostphiqtzadge.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVqZWRmeW5vc3RwaGlxdHphZGdlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3OTEzNzQxMDIsImV4cCI6MjEwNjk1MDEwMn0.hfE33BCeAvyK4ZaaRlOTPqNbJ4UwuvsIKzAwBYd7acI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});